version: "3"
services:
  app:
    image: php:7.4-apache
    restart: unless-stopped
    ports:
      - "3100:80"
    volumes:
      - .:/var/www/html
    command: ["apache2-foreground"]
    env_file: .env

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
