name: deploy

on:
  push:
    branches: deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/env/${{github.event.repository.name}}
            ls -la

            sudo git pull

            sudo touch .env
            sudo chmod 666 .env
            ls -la


            sudo echo '${{ secrets.APP_ENV }}' > .env
            sudo docker-compose down
            sudo docker-compose up -d
