name: deploy

on:
  push:
    branches: deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/env/${{github.event.repository.name}}

            sudo git pull
            sudo chmod +x entrypoint.sh


            sudo echo '${{ secrets.APP_ENV }}' > .env

            composer install

            sudo docker-compose down
            sudo docker-compose up -d
